.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH gping 1  "gping " 
.SH NAME
gping \- Ping, but with a graph.
.SH SYNOPSIS
\fBgping\fR [\fB\-\-cmd\fR] [\fB\-n\fR|\fB\-\-watch\-interval\fR] [\fB\-b\fR|\fB\-\-buffer\fR] [\fB\-4 \fR] [\fB\-6 \fR] [\fB\-i\fR|\fB\-\-interface\fR] [\fB\-s\fR|\fB\-\-simple\-graphics\fR] [\fB\-\-vertical\-margin\fR] [\fB\-\-horizontal\-margin\fR] [\fB\-c\fR|\fB\-\-color\fR] [\fB\-\-clear\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIHOSTS_OR_COMMANDS\fR] 
.SH DESCRIPTION
Ping, but with a graph.
.SH OPTIONS
.TP
\fB\-\-cmd\fR
Graph the execution time for a list of commands rather than pinging hosts
.TP
\fB\-n\fR, \fB\-\-watch\-interval\fR=\fIWATCH_INTERVAL\fR
Watch interval seconds (provide partial seconds like \*(Aq0.5\*(Aq). Default for ping is 0.2, default for cmd is 0.5.
.TP
\fB\-b\fR, \fB\-\-buffer\fR=\fIBUFFER\fR [default: 30]
Determines the number of seconds to display in the graph.
.TP
\fB\-4\fR
Resolve ping targets to IPv4 address
.TP
\fB\-6\fR
Resolve ping targets to IPv6 address
.TP
\fB\-i\fR, \fB\-\-interface\fR=\fIINTERFACE\fR
Interface to use when pinging
.TP
\fB\-s\fR, \fB\-\-simple\-graphics\fR
Uses dot characters instead of braille
.TP
\fB\-\-vertical\-margin\fR=\fIVERTICAL_MARGIN\fR [default: 1]
Vertical margin around the graph (top and bottom)
.TP
\fB\-\-horizontal\-margin\fR=\fIHORIZONTAL_MARGIN\fR [default: 0]
Horizontal margin around the graph (left and right)
.TP
\fB\-c\fR, \fB\-\-color\fR=\fIcolor\fR
Assign color to a graph entry.

This option can be defined more than once as a comma separated string, and the
order which the colors are provided will be matched against the hosts or
commands passed to gping.

Hexadecimal RGB color codes are accepted in the form of \*(Aq#RRGGBB\*(Aq or the
following color names: \*(Aqblack\*(Aq, \*(Aqred\*(Aq, \*(Aqgreen\*(Aq, \*(Aqyellow\*(Aq, \*(Aqblue\*(Aq, \*(Aqmagenta\*(Aq,
\*(Aqcyan\*(Aq, \*(Aqgray\*(Aq, \*(Aqdark\-gray\*(Aq, \*(Aqlight\-red\*(Aq, \*(Aqlight\-green\*(Aq, \*(Aqlight\-yellow\*(Aq,
\*(Aqlight\-blue\*(Aq, \*(Aqlight\-magenta\*(Aq, \*(Aqlight\-cyan\*(Aq, and \*(Aqwhite\*(Aq
.TP
\fB\-\-clear\fR
Clear the graph from the terminal after closing the program
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIHOSTS_OR_COMMANDS\fR]
Hosts or IPs to ping, or commands to run if \-\-cmd is provided. Can use cloud shorthands like aws:eu\-west\-1.
.SH AUTHORS
Tom Forbes <tom@tomforb.es>
