[package]
name = "gping"
version = "1.21.0"
authors = ["Tom Forbes <tom@tomforb.es>"]
edition = "2018"
repository = "https://github.com/orf/gping"
license = "MIT"
description = "Ping, but with a graph."
readme = "../readme.md"

[dependencies]
pinger = { version = "^2.2.0", path = "../pinger" }
tui = { package = "ratatui", version = "0.30.2", features = ["crossterm"], default-features = false }
anyhow = "1.0.101"
chrono = "0.4.43"
itertools = "0.15.0"
clap = { version = "4.5.57", features = ["derive"] }
clap_mangen = "0.3.0"
idna = "1.1.0"
clap-cargo = "0.19.0"
